[package]
name = "async-io"
version = "0.1.1"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
description = "Async I/O and timers"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/stjepang/async-io"
homepage = "https://github.com/stjepang/async-io"
documentation = "https://docs.rs/async-io"
keywords = ["mio", "epoll", "kqueue", "iocp", "wepoll"]
categories = ["asynchronous", "network-programming", "os"]
readme = "README.md"

[dependencies]
concurrent-queue = "1.1.1"
futures-io = { version = "0.3.5", default-features = false, features = ["std"] }
futures-util = { version = "0.3.5", default-features = false, features = ["std", "io"] }
libc = "0.2.71"
once_cell = "1.4.0"
parking = "1.0.3"
slab = "0.4.2"
socket2 = { version = "0.3.12", features = ["pair", "unix"] }

[target.'cfg(windows)'.dependencies]
wepoll-sys-stjepang = "1.0.6"
winapi = { version = "0.3.8", features = ["ioapiset"] }

[dev-dependencies]
async-channel = "1.1.1"
async-dup = "1.1.0"
blocking = "0.4.6"
futures = { version = "0.3.5", default-features = false, features = ["std"] }
tempfile = "3.1.0"
